Add CMake as a secondary build system.
losalamos/LATTE pull request #11
Opened 2017-09-07 21:38 UTC by junghans

2017-09-07 21:51 UTC, cnegre approved these changes

2017-09-08 21:30 UTC, junghans commented
Needed for LLNL/spack#5315

2017-09-13 16:12 UTC, nicolasbock requested changes
Looks great! Could you squash all of those commits? I don't see the point in putting all of the fixups into git.

2017-09-13 16:21 UTC, cnegre approved these changes

2017-09-13 16:22 UTC, merged